npmPublishAccess: public
npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  relefant:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true

preferInteractive: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.4.cjs
